//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Data
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class DBObject
	{
		public virtual int id
		{
			get;
			set;
		}

		public virtual object objectType
		{
			get;
			set;
		}

		public virtual void Pull()
		{
			throw new System.NotImplementedException();
		}

		public virtual void Push()
		{
			throw new System.NotImplementedException();
		}

		public virtual void TryDelete()
		{
			throw new System.NotImplementedException();
		}

	}
}

