//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Data
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Invoice : DBObject
	{
		public virtual Member member
		{
			get;
			set;
		}

		public virtual CostModifier age_modifier
		{
			get;
			set;
		}

		public virtual CostModifier job_modifier
		{
			get;
			set;
		}

		public virtual DateTime date
		{
			get;
			set;
		}

		public virtual Decimal calculated_cost
		{
			get;
			set;
		}

		public virtual Decimal paid_cost
		{
			get;
			set;
		}

		public virtual bool is_fee
		{
			get;
			set;
		}

		public virtual void Pay(Payment payment)
		{
			throw new System.NotImplementedException();
		}

	}
}

