//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Data
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Payment : DBObject
	{
		public virtual DateTime date
		{
			get;
			set;
		}

		public virtual Invoice invoice
		{
			get;
			set;
		}

		public virtual BankAccount bank
		{
			get;
			set;
		}

		public virtual bool bank_was_sepa
		{
			get;
			set;
		}

		public virtual Decimal amount
		{
			get;
			set;
		}

	}
}

