//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace SerWalterClient.Data
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class BankAccount : DBObject
	{
		public virtual string iban
		{
			get;
			set;
		}

		public virtual string bic
		{
			get;
			set;
		}

		public virtual string institute_name
		{
			get;
			set;
		}

		public virtual string holder_name
		{
			get;
			set;
		}

	}
}

