//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace SerWalterClient.Data
{
    using System.ComponentModel;

    public class BankAccount : DBObject
    {
        [DisplayName("IBAN")]
        public virtual string iban
        {
            get;
            set;
        }

        [DisplayName("BIC/SWIFT")]
        public virtual string bic
        {
            get;
            set;
        }

        [DisplayName("Bankname")]
        public virtual string institute_name
        {
            get;
            set;
        }

        [DisplayName("Kontoinhaber")]
        public virtual string holder_name
        {
            get;
            set;
        }

        public override string ToString()
        {
            return string.Format("{0} - {1} - {2}", holder_name, institute_name, iban);
        }
    }
}