//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace SerWalterClient.Data
{
    using Newtonsoft.Json;
    using System;
    using System.ComponentModel;

    public class Invoice : DBObject
    {
        [DisplayName("Mitglied")]
        public virtual int member_id
        {
            get;
            set;
        }

        [Browsable(false)]
        public virtual int age_modifier
        {
            get;
            set;
        }

        [Browsable(false)]
        public virtual int job_modifier
        {
            get;
            set;
        }

        [JsonConverter(typeof(DBDateTime))]
        [DisplayName("Datum")]
        public virtual DateTime date
        {
            get;
            set;
        }

        [DisplayName("Betrag")]
        public virtual Decimal calculated_cost
        {
            get;
            set;
        }

        [DisplayName("Beglichen")]
        public virtual Decimal paid_cost
        {
            get;
            set;
        }

        [DisplayName("Ist Gebühr")]
        [JsonConverter(typeof(DBBoolean))]
        public virtual bool is_fee
        {
            get;
            set;
        }

        public virtual void Pay(Payment payment)
        {
            throw new System.NotImplementedException();
        }
    }
}